CREATE TABLE IF NOT EXISTS user_state (
    chat_id VARCHAR(50) PRIMARY KEY,
    level VARCHAR(50) NOT NULL DEFAULT 'start',
    data TEXT,
    mes_id VARCHAR(50),
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);